name: sdg
channels:
  - pytorch
  - defaults
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
dependencies:
  - blas=1.0
  - ca-certificates=2023.08.22
  - certifi=2023.7.22
  - cudatoolkit=11.8.0
  - filelock=3.9.0
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - libuv=1.44.2
  - markupsafe=2.1.1
  - mkl=2023.1.0
  - mpmath=1.3.0
  - networkx=3.1
  - openssl=3.0.10
  - pip=23.2.1
  - python=3.9.17
  - pytorch-mutex=1.0
  - setuptools=68.0.0
  - sqlite=3.41.2
  - sympy=1.11.1
  - tbb=2021.8.0
  - typing_extensions=4.7.1
  - wheel=0.38.4
  - pip:
      - absl-py==1.4.0
      - attrs==24.2.0
      - cachetools==5.3.1
      - charset-normalizer==3.2.0
      - chex==0.1.86
      - colorama==0.4.6
      - contourpy==1.1.1
      - cycler==0.12.1
      - dataclasses==0.6
      - dm-tree==0.1.8
      - dp-accounting==0.4.4
      - einops==0.7.0
      - etils==1.5.2
      - fonttools==4.43.1
      - google-auth==2.22.0
      - google-auth-oauthlib==1.0.0
      - grad-cam==1.4.0
      - grpcio==1.58.0
      - idna==3.4
      - imageio==2.34.0
      - importlib-metadata==6.8.0
      - importlib-resources==6.1.0
      - jax==0.4.30
      - jaxlib==0.4.30
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - markdown==3.4.4
      - matplotlib==3.8.0
      - ml-dtypes==0.4.0
      - numpy==1.24.1
      - oauthlib==3.2.2
      - opacus==1.4.0
      - opencv-python==4.9.0.80
      - opt-einsum==3.3.0
      - optax==0.2.3
      - packaging==23.2
      - pandas==2.2.2
      - phe==1.5.0
      - pillow==10.0.0
      - protobuf==4.24.3
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pytz==2024.1
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scikit-learn==1.4.1.post1
      - scipy==1.11.2
      - six==1.16.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.1
      - threadpoolctl==3.4.0
      - toolz==0.12.1
      - torchcam==0.4.0
      - tqdm==4.66.1
      - ttach==0.0.3
      - tzdata==2024.1
      - urllib3==1.26
      - utils==1.0.2
      - werkzeug==2.3.7
      - zipp==3.16.2
